import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import TopicMenu from "@/components/TopicMenu";

const montserrat = Montserrat({ subsets: ["latin"], weight: ['700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Menu = <TopicMenu />

  return (
    <html lang="en" className={montserrat.className}>
      <body style={{margin: 0}}>
        <Navbar menu={Menu} />
        {children}
      </body>
    </html>
  );
}
